import forms from '@tailwindcss/forms';
import typography from '@tailwindcss/typography';

export default {
    darkMode: 'class',
    content: [
        './resources/**/*.blade.php',
        './resources/**/*.js',
        './app/View/Components/**/*.php',
    ],
    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
            },
            colors: {
                brand: {
                    50: '#eff6ff',
                    100: '#dbeafe',
                    200: '#bfdbfe',
                    300: '#93c5fd',
                    400: '#60a5fa',
                    500: '#2563eb',
                    600: '#1d4ed8',
                    700: '#1e40af',
                    800: '#1e3a8a',
                    900: '#172554',
                    950: '#0b1228',
                },
                executive: {
                    50: '#fffbeb',
                    100: '#fef3c7',
                    400: '#fbbf24',
                    500: '#f59e0b',
                    600: '#d97706',
                },
                command: {
                    50: '#f8fafc',
                    100: '#eef2ff',
                    800: '#1f2354',
                    900: '#101326',
                    950: '#070918',
                },
                'surface-bright': '#f8f9ff',
                'on-surface-variant': '#434652',
                'surface-container-low': '#eff4ff',
                'on-primary': '#ffffff',
                'primary-container': '#1e4fa8',
                'on-error': '#ffffff',
                'secondary-fixed-dim': '#a4c9ff',
                'on-secondary-fixed': '#001c39',
                'on-primary-container': '#b2c7ff',
                'inverse-primary': '#b0c6ff',
                'tertiary-container': '#24548d',
                'secondary-fixed': '#d4e3ff',
                primary: '#003887',
                'surface-container-highest': '#d3e4fe',
                'on-tertiary-fixed-variant': '#124780',
                'on-primary-fixed-variant': '#04429b',
                tertiary: '#003c73',
                'surface-variant': '#d3e4fe',
                'tertiary-fixed': '#d4e3ff',
                background: '#f8f9ff',
                'surface-container': '#e5eeff',
                surface: '#f8f9ff',
                'tertiary-fixed-dim': '#a5c8ff',
                'on-error-container': '#93000a',
                'error-container': '#ffdad6',
                'surface-dim': '#cbdbf5',
                'surface-container-lowest': '#ffffff',
                'outline-variant': '#c3c6d4',
                'inverse-on-surface': '#eaf1ff',
                error: '#ba1a1a',
                'surface-container-high': '#dce9ff',
                secondary: '#1960a6',
                'on-surface': '#0b1c30',
                'on-tertiary': '#ffffff',
                'on-secondary': '#ffffff',
                'on-background': '#0b1c30',
                'on-secondary-fixed-variant': '#004883',
                'inverse-surface': '#213145',
                'secondary-container': '#7ab3ff',
                'on-tertiary-container': '#a7c9ff',
                'surface-tint': '#2d5bb4',
                'on-primary-fixed': '#001945',
                outline: '#737783',
                'primary-fixed-dim': '#b0c6ff',
                'on-secondary-container': '#00447e',
                'primary-fixed': '#d9e2ff',
                'on-tertiary-fixed': '#001c3a',
            },
            boxShadow: {
                command: '0 24px 70px rgba(5, 8, 22, 0.18)',
                glow: '0 0 0 1px rgba(96, 165, 250, 0.22), 0 18px 45px rgba(14, 165, 233, 0.13)',
            },
        },
    },
    plugins: [forms, typography],
};
